### PR TITLE
Remove NGINX installation and configuration sections from Ubuntu intallation guide

### PR DESCRIPTION
**Pull request by mtuchowski**

### CODE REVIEW

**Comment by mtuchowski** [comment]
@medikoo FYI

**Comment by medikoo** [comment]
It has some conflicts

**Comment by melux** [comment]
@mtuchowski can you make this again from a new branch from master please ? You'll have less troubles than solving conflicts I think...

**Comment by medikoo** [comment]
@mtuchowski nGinx section is valuable, so instead of removing  let's move it to: Installation -> Optional software -> nGinx

**Comment by mtuchowski** [comment]
@melux I kept this pull-request and resolved conflicts (console git did not have any problems to do this automatically).

**Pull request merged**
